language: ruby
rvm:
  #- 1.8.7
  - 1.9.2
  - 1.9.3
  #- jruby-18mode # JRuby in 1.8 mode
  #- jruby-19mode # JRuby in 1.9 mode
  #- rbx-18mode
  #- rbx-19mode
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
# uncomment this line if your project needs to run something other than `rake`:
script: 
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - mysql -e 'create database sample_app_test'
  - psql -c 'create database sample_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs