language: ruby
rvm:
  - 1.9.3
env:
  global:
    # These variables need to be changed for personalized deployment
    # See README for details
    - secure: "YZLEEev+JQoqlThsreCS0Px3LPMgQJX8BCquS7jsXsBG5FZba00tEdhviL5Z\nQurx5rsO0YS6dW3PA1yl+H+npro4FBpfMTV0tU+FrfO19h08Gro7cBwTxqlI\nOp0Zje4u/e4lMA1NQFcM+z/SUqr7tWkFraXb+AWby9ZQQG7Klm8="
    - secure: "T1wvWm84s5OdDk6PzYmteboEnaGLWiOW1qvoIjwg3PXByZXcDsb3I8Kp9Sg3\nk5EoUmZyrWSlIvpTgyPP2eyncnn6IktB1Qa5sllbS/g/XP1MqGl6pJtsEDnm\n/ongBWdg6pzQKAeAcN4puQzXWu69F2AnaCJroTKrNaMmI/Y1uJw="
    - secure: "no/EIYkKUaHn8E4joAoPkcjwGs/3DdOdt5NwjEI8TzIRXO2qofT8I/n1IRuv\ntHILoVgkn3K0TOQOq/bm+k+AV5ALQNkdsX1WYmdlgLLIIJLYeVWngXWx/5vr\nIGD+KXOWPsH7IZkCvYmxVTxtQ4cYTxuOv9hJd8CtNmHPxUbKdwA="
    - secure: "HP6yVsrQs52HgpH6nXMzRpD4oqL+RzdYyyQQifdu03vlK+7qdAfd0lseH/m7\nMDIGNil0ZIf/yODWrL4Qo4vFbX1ZMx3Cv/2MqWh6XbaX+i9wn3SX1Y1Jmupj\ngZc9QtyYxRN0ylDUs01s2/kv8dZjRvd+5DobRw0JbSKRg8+2ea4="
    - secure: "GvE31eHzRLzPJlp5OGvkIrMNzhj8wY1e0h1L21INxeBdhnxO7Notaw5W9Aa5\nf6U1VxkCOI7H3yPvHGwurCG9p5tdLGdLfy/0G43/4uZP10bXerK6UPpBawBz\nRxIXw/rPyED/czSN7ZmLSvE1N4vZtDWgO7w9fl+1glXh66IPytw="
  matrix:
    - DB: postgresql
bundler_args: --binstubs=./bundler_stubs --without development
before_script:
  - psql -c "create database $APP_DB_NAME_TEST;" -U $APP_DB_USER
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  # - bundle exec rake db:test:prepare
  # - psql -c 'create database sample_app_production;' -U postgres
script:
  - bundle exec rspec --no-drb --format progress spec/
  # heroku labs:enable user-env-compile -a [app-name]
  # enabled so no need to precompile assets before deploy anymore
  # - bundle exec rake assets:precompile
after_success:
  # - git add public/assets
  # - git commit -m "Precompile assets"
  - gem install heroku
  - git remote add heroku $HEROKU_GIT_URL
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear current Heroku SSH keys
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  - yes | git push heroku master