# sqlite: &sqlite
#   adapter: sqlite3
#   database: db/<%= Rails.env %>.sqlite3

# mysql: &mysql
#   adapter: mysql2
#   username: root
#   password:
#   database: <%= Rails.root.basename.to_s %>_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: <%= ENV['APP_DB_USER'] %>
  password: <%= ENV['APP_DB_PASSWORD'] %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  database: <%= ENV['APP_DB_NAME_DEV'] %>
  <<: *defaults

test: &test
  database: <%= ENV['APP_DB_NAME_TEST'] %>
  <<: *defaults

production:
  database: <%= ENV['APP_DB_NAME_PROD'] %>
  <<: *defaults

cucumber:
  <<: *test